version: '3.8'
services:
  kafka1:
    image: apache/kafka:3.7.0
    container_name: kafka1
    # environment:
    #   - KAFKA_KRAFT_MODE=controller
    #   - KAFKA_KRAFT_BROKER_ID=1
    #   - KAFKA_KRAFT_LISTENERS=PLAINTEXT://:9092
    #   - KAFKA_KRAFT_LOG_DIRS=/var/lib/kafka/data
    #   - KAFKA_KRAFT_AUTO_CREATE_TOPICS_ENABLE=false
    # volumes:
    #   - ./data/kafka1:/var/lib/kafka/data
    ports:
      - 9092:9092
